
## 1️ Normalization (Min-Max Scaling)

**Definition:**  
Normalization rescales features into a fixed range, usually [0, 1].

$$
x' = \frac{x - x_{min}}{x_{max} - x_{min}}
$$

**Properties:**  
- Minimum of feature → 0  
- Maximum of feature → 1  
- Keeps the shape of the original distribution but changes the scale  

**When to use:**  
- Useful for algorithms based on distances (kNN, K-Means, PCA)  
- Often applied in neural networks  



In [1]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

X = np.array([[1, 200],
              [2, 300],
              [3, 400]])

scaler = MinMaxScaler()
X_norm = scaler.fit_transform(X)

print("Original:\n", X)
print("Normalized:\n", X_norm)

Original:
 [[  1 200]
 [  2 300]
 [  3 400]]
Normalized:
 [[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


# Standardization (Z-score Scaling)

## Definition
Standardization transforms data so that it has **mean = 0** and **standard deviation = 1**.

$$
x' = \frac{x - \mu}{\sigma}
$$



## Properties
- Centered around **0**  
- Unit variance (**1**)  
- More robust when data has outliers  



## When to use
- Good for **linear models** (Linear/Logistic Regression)  
- Often used with **SVM, PCA**  



In [ ]:
from sklearn.preprocessing import StandardScaler
import numpy as np

X = np.array([[1, 200],
              [2, 300],
              [3, 400]])

scaler = StandardScaler()
X_std = scaler.fit_transform(X)

print("Original:\n", X)
print("Standardized:\n", X_std)

Original:
 [[  1 200]
 [  2 300]
 [  3 400]]
Standardized:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
